version: '3.8'

services:
  hotelsdb:
    image: postgres:alpine3.18
    volumes:
      - ./hotels_db:/var/lib/postgresql/data
    container_name: hotels_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  hotels_api:
    container_name: hotels_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - hotelsdb
    ports:
      - '5000:5000'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - hotels_api
    container_name: hotels_nginx
    expose:
      - 80
